# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
    build_gcc_latest_cpp17:
        docker:
            - image: gcc:latest
        steps:
            - checkout
            - run: cp refl.hpp test/ && g++ -std=c++17 test/010-TestCase.cpp
            - run: ./a.out
    build_clang_latest_cpp17:
        docker:
            - image: centos/llvm-toolset-7-centos7:latest
        steps:
            - checkout
            - run: cp refl.hpp test/ && clang++ -std=c++17 test/010-TestCase.cpp
            - run: ./a.out

# Orchestrate or schedule a set of jobs
workflows:
    build_and_test:
        jobs:
            - build_gcc_latest_cpp17
            - build_clang_latest_cpp17
